---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-sync
  namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend
    app: master-sync
spec:
  selector:
    matchLabels:
      app: master-sync
  replicas: 1
  template:
    metadata:
      labels:
        app: master-sync
        run: master-sync
    spec:
      hostname: master-sync
      restartPolicy: Always
      nodeSelector:
        mode: "backend"
      imagePullSecrets:
        - name: imagepullsecret
      containers:
      - name: master-sync
        image: "{{ .Values.global.images.mastersync }}"
        imagePullPolicy: {{ .Values.global.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: 16180
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - '-c'
            - pgrep npm -a
        volumeMounts:
        - name: master-sync-logs
          mountPath: "/var/www/html/master-sync-service-logs"
        - name: tz-config
          mountPath: /etc/localtime
          readOnly: true
        - name: cluster-local-cert-volume
          mountPath: "/usr/local/share/ca-certificates/cluster.local/"
          readOnly: true
        envFrom:
        - configMapRef:
            name: master-sync-env
        - configMapRef:
            name: global-env
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: CONSUL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: CONSUL_SERVER
          value: $(CONSUL_AGENT)
      volumes:
      - name: master-sync-logs
        hostPath:
           path: /storage/gateway-logs
           type: DirectoryOrCreate
#        flexVolume:
#          driver: ceph.rook.io/rook
#          fsType: ceph
#          options:
#            fsName: myfs # name of the filesystem specified in the filesystem CRD.
#            clusterNamespace: rook-ceph
      - name: cluster-local-cert-volume
        secret:
          secretName: cluster-local-cert
      - name: tz-config
        hostPath:
           path: /etc/localtime
           type: File
