apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-env
  namespace: {{ .Release.Namespace }}
  labels:
    ConfigMap: apigateway-env
data:
    GATEWAY_PORT: "8080"
    GATEWAY_SECURE_PORT: "9443"
    GATEWAY_HOST: "apigateway.tls.ai"                    ## BLOCK REQUESTS NOT ORIGINATING FROM THIS DOMAIN
    #GATEWAY_HOST: '"*"'
    TLS_DOMAIN: "*.tls.ai"                               ## DO NOT CHANGE
    #ALLOW_CROS: '*'
    ALLOW_CROS: 'tls.ai,default.svc.cluster.local'       ## CORS DOMAIN WHITELIST
    API_PORT: "5443"
    API_HOST: "api.{{ .Release.Namespace }}.svc.cluster.local"
    DASH_API_URL: "https://api.{{ .Release.Namespace }}.svc.cluster.local:5443"
    GATEWAY_SECURE_URL: "https://apigateway.{{ .Release.Namespace }}.svc.cluster.local:9443"
    GATEWAY_URL: "http://apigateway.{{ .Release.Namespace }}.svc.cluster.local:8080"
    JWT_API_PUBKEY_PATH: "config/keys/bettertomorrowJwtSecret.pem"
    DASH_API_PUBLIC_URL: "http://api.{{ .Release.Namespace }}.svc.cluster.local:3000"
    RUN_AS_USER: "user"
    ## API GW Token EXPIRY-  represents seconds default : 86400 (24 hours) or 99999999 (3 years from now)
    JWT_EXPIRY_DURATION: "86400"
    API_JWT_SECRET: "thehouseisonfire"
    #IS_FORCE_JWT_SECRET_CHANGE: false
    REDIS_HOST: "127.0.0.1"
    REDIS_PORT: "6379"
    ## logging services (chaperone init)
    ENABLE_DOCKER_STDOUT: "true"
    ENABLE_DOCKER_LOG: "true"
    #LOG_ROTATE_MAX_SIZE: 200m
    #LOG_ROTATE_MAX_FILES: 14d
    #LOG_ROTATE_DATE_PATTERN: YYYY-MM-DD
    PUSH_NOTIFICATION_URL: https://push-notification.{{ .Release.Namespace }}.svc.cluster.local:7443
    KEYS_DIR: "/home/user/api-gateway/config/keys"
    KEY_NAME: "bettertomorrowJwtSecret.pem"
