apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: redis-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
    #"helm.sh/hook-delete-policy": "before-hook-creation"   
stringData:
  password: {{ randAlphaNum 10 | sha256sum | b64enc | trunc 32 }}
