apiVersion: v1
kind: ConfigMap
metadata:
  name: broadcaster-env
  namespace: {{ .Release.Namespace }}
  labels:
    ConfigMap: broadcaster-env
data:
    ## Logging (chaperone init)
    ENABLE_DOCKER_STDOUT: "true"
    ENABLE_DOCKER_LOG: "false"

    ## General
    #BCAST_TIME_SHIFT_MS: 0

    ## RabbitMQ - enables support for api master
    BCAST_RMQ_IS_ENABLED: "false"
    #: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq"
    BCAST_RMQ_ONLY_SUBJECTS: "true"

    ## Mailer - enables email alerts
    #BCAST_MAILER_IS_ENABLED: "false"
    #BCAST_MAILER_USERNAME:
    #BCAST_MAILER_PASS:
    #BCAST_MAILER_RECIPIENTS:
    #BCAST_MAILER_FROM_EMAIL:
    #BCAST_MAILER_SENDER_NAME:
    #BCAST_MAILER_SUBJECT: "[AnyVision]_Alert!""
    #BCAST_MAILER_TEMPLATE_RELATIVE_PATH: ""./emailTemplate.html"
    #BCAST_MAILER_SKIP_SECONDS: "60"
    #BCAST_MAILER_EXCHANGE_PORT: "587"
    #BCAST_MAILER_EXCHANGE_WITH_TLS: "false"
    #BCAST_MAILER_EXCHANGE_HOST: "localhost"
    #BCAST_MAILER_IS_WITH_AUTH: "true"


    ## Wiegand Card-ID integration
    #BCAST_WIEGAND_IS_ENABLED: "false"

    ## Multicast broadcaster
    #BCAST_MCAST_IS_ENABLED: "false"

    ## Socket.io
    #BCAST_SOCKETIO_API_URL: "https://apigateway.{{ .Release.Namespace }}.svc.cluster.local:5443"
    #BCAST_SOCKETIO_IS_SECURE: "false"

    ## Directories
    #BCAST_MAPPER: "/home/user/Broadcaster/mappers/passthrough"
    #BCAST_PLUGIN_DIRECTORY: "/home/user/Broadcaster/plugins"
    api_service_ip: "api.{{ .Release.Namespace }}.svc.cluster.local"
    BCAST_SOCKETIO_API_URL: "https://api.{{ .Release.Namespace }}.svc.cluster.local:5443"
    RMQ_HOST: "rabbitmq.{{ .Release.Namespace }}.svc.cluster.local"
    RMQ_PORT: "5672"
    RUN_AS_USER: "user"
    ENABLE_CHOWN: "false"
    ENABLE_DOCKER_STDOUT: "true"
    ENABLE_DOCKER_LOG: "false"
    BCAST_RMQ_ONLY_SUBJECTS: "true"
