---
apiVersion: v1
kind: Service
metadata:
  name: webrtc
  namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend
    app: webrtc
spec:
  clusterIP: None
  ports:
  - name: "webrtc-streamer-8000"
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: "coturn-3478"
    port: 3478
    targetPort: 3478
    protocol: TCP
  selector:
    run: webrtc
