apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-notification
  namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend
    app: push-notification
spec:
  selector:
    matchLabels:
      app: push-notification
  replicas: 1
  template:
    metadata:
      labels:
        app: push-notification
        run: push-notification
    spec:
      hostname: push-notification
      restartPolicy: Always
      nodeSelector:
        mode: "backend"
      imagePullSecrets:
        - name: imagepullsecret
      containers:
      - name: push-notification
        image: "{{ .Values.global.images.pushNotification }}"
        imagePullPolicy: {{ .Values.global.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: 7443
        readinessProbe:
          httpGet:
            path: /
            port: 7443
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 10
        volumeMounts:
        - name: storage-data
          mountPath: "/var/www/html"
        - name: tz-config
          mountPath: /etc/localtime
          readOnly: true
        - name: cluster-local-cert-volume
          mountPath: "/usr/local/share/ca-certificates/cluster.local/"
          readOnly: true
        envFrom:
        - configMapRef:
            name: push-notification-env
        - configMapRef:
            name: global-env
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password              
        - name: CONSUL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: CONSUL_SERVER
          value: $(CONSUL_AGENT)
      volumes:
      - name: cluster-local-cert-volume
        secret:
          secretName: cluster-local-cert
      - name: tz-config
        hostPath:
           path: /etc/localtime
           type: File
      - name: storage-data
        hostPath:
           path: /storage
           type: DirectoryOrCreate
