apiVersion: v1
kind: Service
metadata:
  name: push-notification
  namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend
    app: push-notification
spec:
  clusterIP: None
  ports:
  - name: "push-notification-7443"
    port: 7443
    targetPort: 7443
    protocol: TCP
  selector:
    run: push-notification
