{{- if (or (and (ne (.Values.client.enabled | toString) "-") .Values.client.enabled) (and (eq (.Values.client.enabled | toString) "-") .Values.global.enabled)) }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "consul.name" . }}-client
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.global.enablePodSecurityPolicies }}
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames:
    - {{ template "consul.name" . }}-client
    verbs:
    - use
{{- end }}
{{- end }}
