apiVersion: v1
kind: Service
metadata:
 name: {{ template "seaweedfs.name" . }}-filer
 namespace: {{ .Release.Namespace }}
 labels:
    app: {{ template "seaweedfs.name" . }}
    component: filer
spec:
 clusterIP: None
 ports:
 - name: "swfs-filer"
   port: {{ .Values.filer.port }}
   targetPort: {{ .Values.filer.port }}
   protocol: TCP
 selector:
    app: {{ template "seaweedfs.name" . }}
    component: filer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "seaweedfs.name" . }}-master
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "seaweedfs.name" . }}
    component: master
spec:
  clusterIP: None
  ports:
  - name: "swfs-master"
    port: {{ .Values.master.port }}
    targetPort: {{ .Values.master.port }}
    protocol: TCP
  selector:
    app: {{ template "seaweedfs.name" . }}
    component: master
---
apiVersion: v1
kind: Service
metadata:
 name: {{ template "seaweedfs.name" . }}-s3
 namespace: {{ .Release.Namespace }}
 labels:
    app: {{ template "seaweedfs.name" . }}
    component: s3
spec:
 clusterIP: None
 ports:
 - name: "swfs-s3"
   port: {{ .Values.s3.port }}
   targetPort: {{ .Values.s3.port }}
   protocol: TCP
 selector:
    app: {{ template "seaweedfs.name" . }}
    component: s3
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress-{{ template "seaweedfs.name" . }}-filer
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/service-upstream: "true"
   nginx.ingress.kubernetes.io/rewrite-target: /$1
   nginx.ingress.kubernetes.io/use-regex: "true"
   nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
   nginx.ingress.kubernetes.io/ssl-redirect: "false"
   nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
   nginx.ingress.kubernetes.io/configuration-snippet: |
     sub_filter '<head>' '<head> <base href="/sw-filer/">'; #add base url
     sub_filter '="/' '="./';                               #make absolute paths to relative
     sub_filter '=/' '=./';
     sub_filter '/seaweedfsstatic' './seaweedfsstatic';
     sub_filter_once off;
spec:
 rules:
 - http:
     paths:
     - path: /sw-filer/?(.*)
       backend:
         serviceName: {{ template "seaweedfs.name" . }}-filer
         servicePort: {{ .Values.filer.port }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-{{ template "seaweedfs.name" . }}-master
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter '<head>' '<head> <base href="/sw-master/">'; #add base url
      sub_filter '="/' '="./';                                #make absolute paths to relative
      sub_filter '=/' '=./';
      sub_filter '/seaweedfsstatic' './seaweedfsstatic';
      sub_filter_once off;
spec:
  rules:
  - http:
      paths:
      - path: /sw-master/?(.*)
        backend:
          serviceName: {{ template "seaweedfs.name" . }}-master
          servicePort: {{ .Values.master.port }}
