{{- if .Values.volume.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "seaweedfs.name" . }}-volume
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "seaweedfs.name" . }}
    chart: {{ template "seaweedfs.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ template "seaweedfs.name" . }}-volume
  selector:
    matchLabels:
      app: {{ template "seaweedfs.name" . }}
      chart: {{ template "seaweedfs.chart" . }}
      release: {{ .Release.Name }}
      component: volume
  template:
    metadata:
      labels:
        app: {{ template "seaweedfs.name" . }}
        chart: {{ template "seaweedfs.chart" . }}
        release: {{ .Release.Name }}
        component: volume
    spec:
      restartPolicy: {{ default .Values.global.restartPolicy .Values.volume.restartPolicy }}
      {{- if .Values.volume.tolerations }}
      tolerations:
        {{ tpl .Values.volume.tolerations . | nindent 8 | trim }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.volume.priorityClassName }}
      priorityClassName: {{ .Values.volume.priorityClassName | quote }}
      {{- end }}
      containers:
        - name: seaweedfs
          image: "{{ default .Values.global.image .Values.volume.image }}"
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.volume.imagePullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - "/bin/sh"
            - "-ec"
            - |
              SEAWEEDFS_FULLNAME="{{ template "seaweedfs.name" . }}"

              exec /usr/bin/weed volume \
                -port={{ .Values.volume.port }} \
                -dir={{ .Values.volume.dir }} \
                -max={{ .Values.volume.maxVolumes }} \
                {{- if .Values.volume.rack }}
                -rack={{ .Values.volume.rack }} \
                {{- end }}
                {{- if .Values.volume.dataCenter }}
                -dataCenter={{ .Values.volume.dataCenter }} \
                {{- end }}
                -ip.bind={{ .Values.volume.ipBind }} \
                -read.redirect={{ .Values.volume.readRedirect }} \
                {{- if .Values.volume.whiteList }}
                -whiteList={{ .Values.volume.whiteList }} \
                {{- end }}
                {{- if .Values.volume.imagesFixOrientation }}
                -images.fix.orientation \
                {{- end }}
                -ip=${POD_IP} \
                -mserver={{ range $index := until (.Values.master.replicas | int) }}${SEAWEEDFS_FULLNAME}-master-{{ $index }}.${SEAWEEDFS_FULLNAME}-master:{{ $.Values.master.port }}{{ if lt $index (sub ($.Values.master.replicas | int) 1) }},{{ end }}{{ end }}
          volumeMounts:
            - name: seaweedfs-volume-storage
              mountPath: "/data/"          
            {{- if .Values.global.enableSecurity }}
            - name: security-config
              readOnly: true
              mountPath: /etc/seaweedfs/security.toml
              subPath: security.toml
            - name: ca-cert
              readOnly: true
              mountPath: /usr/local/share/ca-certificates/ca/
            - name: master-cert
              readOnly: true
              mountPath: /usr/local/share/ca-certificates/master/
            - name: volume-cert
              readOnly: true
              mountPath: /usr/local/share/ca-certificates/volume/
            - name: filer-cert
              readOnly: true
              mountPath: /usr/local/share/ca-certificates/filer/
            - name: client-cert
              readOnly: true
              mountPath: /usr/local/share/ca-certificates/client/
            {{- end }}
            {{ tpl .Values.volume.extraVolumeMounts . | nindent 12 | trim }}
          ports:
            - containerPort: {{ .Values.volume.port }}
              name: swfs-volume
          # readinessProbe:
          #   # NOTE(mitchellh): when our HTTP status endpoints support the
          #   # proper status codes, we should switch to that. This is temporary.
          #   exec:
          #     command:
          #       - "/bin/sh"
          #       - "-ec"
          #       - |
          #         curl http://127.0.0.1:8500/v1/status/leader 2>/dev/null | \
          #         grep -E '".+"'
          #   failureThreshold: 2
          #   initialDelaySeconds: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          #   timeoutSeconds: 5
          {{- if .Values.volume.resources }}
          resources:
            {{ tpl .Values.volume.resources . | nindent 12 | trim }}
          {{- end }}
      volumes:
        - name: seaweedfs-volume-storage
          hostPath:
            path: /storage/object_store/
            type: DirectoryOrCreate           
        {{- if .Values.global.enableSecurity }}
        - name: security-config
          configMap:
            name: {{ template "seaweedfs.name" . }}-security-config
        - name: ca-cert
          secret:
            secretName: {{ template "seaweedfs.name" . }}-ca-cert
        - name: master-cert
          secret:
            secretName: {{ template "seaweedfs.name" . }}-master-cert
        - name: volume-cert
          secret:
            secretName: {{ template "seaweedfs.name" . }}-volume-cert
        - name: filer-cert
          secret:
            secretName: {{ template "seaweedfs.name" . }}-filer-cert
        - name: client-cert
          secret:
            secretName: {{ template "seaweedfs.name" . }}-client-cert
        {{- end }}
        {{ tpl .Values.volume.extraVolumes . | indent 8 | trim }}   
      {{- if .Values.volume.nodeSelector }}
      nodeSelector:
        {{ tpl .Values.volume.nodeSelector . | indent 8 | trim }}
      {{- end }}
{{- end }}
