apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx
spec:
  clusterIP: None
  ports:
  - name: "nginx-80"
    port: 80
    targetPort: 80
    protocol: TCP
  - name: "nginx-443"
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    run: nginx