apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend
    app: mongodb
spec:
  clusterIP: None
  ports:
  - name: "mongo-27017"
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    run: mongodb
