apiVersion: v1
kind: Secret
metadata:
  name: ingress-basic-auth-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  auth: YW55dmlzaW9uOiRhcHIxJGkyamJOWjdGJFFQRFRWcVZ3eTR1b1AxSXhvUUdXdy8K
