apiVersion: v1
kind: Service
metadata:
  name: memsql
  namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend
    app: memsql
spec:
  clusterIP: None
  ports:
  - name: "memsql-3306"
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    run: memsql
