# Source: api/templates/cronjob.yaml
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend
    app: api
spec:
  clusterIP: None
  ports:
  - name: "api-5443"
    port: 5443
    targetPort: 5443
    protocol: TCP
  - name: "api-3000"
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    run: api
